/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'receiverPhoneNumber' : string,
  'listingId' : bigint,
  'isRead' : boolean,
  'messageText' : string,
  'timestamp' : bigint,
  'senderPhoneNumber' : string,
}
export type ExternalBlob = Uint8Array;
export interface ProductListing {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'description' : string,
  'timestamp' : bigint,
  'category' : string,
  'image' : ExternalBlob,
  'price' : bigint,
  'sellerPhoneNumber' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createListing' : ActorMethod<
    [string, string, string, bigint, string, ExternalBlob, bigint],
    bigint
  >,
  'deleteListing' : ActorMethod<[bigint, string], undefined>,
  'editListing' : ActorMethod<
    [bigint, string, string, string, bigint, string, ExternalBlob],
    undefined
  >,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllListings' : ActorMethod<[], Array<ProductListing>>,
  'getConversation' : ActorMethod<[string, string, bigint], Array<ChatMessage>>,
  'getListing' : ActorMethod<[bigint], ProductListing>,
  'getListingsByCategory' : ActorMethod<[string], Array<ProductListing>>,
  'getUnreadMessages' : ActorMethod<[string], Array<ChatMessage>>,
  'getUserListings' : ActorMethod<[string], Array<ProductListing>>,
  'markMessagesAsRead' : ActorMethod<[string, string, bigint], undefined>,
  'searchListings' : ActorMethod<[string], Array<ProductListing>>,
  'sendMessage' : ActorMethod<[string, string, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];